services:
  web:
    image: jeffersonp/bolsa-php:latest
    container_name: web-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: jeffersop/bolsa-php:latest
    container_name: php-fpm
    environment:
      - API_BASE=http://web
    depends_on:
      - web